const OK_STATUS_CODE = 200;
const CREATED_STATUS_CODE = 201;
const NOT_VALID_ERROR_CODE = 400;
const NOT_FOUND_ERROR_CODE = 404;
const SERVER_ERROR_CODE = 500;

module.exports = {
  OK_STATUS_CODE,
  CREATED_STATUS_CODE,
  NOT_VALID_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  SERVER_ERROR_CODE,
};
